version: '3'
services:
  wordpress_service:
    container_name: wordpress_service
    image: wordpress
    networks:
      - wordpress-network
    ports:
      - '3000:80'
    depends_on:
      - wordpress_mysql
    volumes:
      - ./html:/var/www/html
  wordpress_mysql:
    container_name: wordpress_mysql
    image: mysql
    environment:
      - MYSQL_USER=wordpress
    env_file:
      - .env
    networks:
      - wordpress-network
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  wordpress-network:
volumes:
  mysql_data:
  

