- name: Setup WordPress with Docker
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:

    - name: Pull WordPress Docker image
      docker_image:
        name: wordpress:latest
        source: pull
        state: present
      become: yes

    - name: Start WordPress container
      docker_container:
        name: wordpress_container
        image: wordpress:latest
        ports:
          - "80:80"
          - "3306:3306"  
        env:
          WORDPRESS_DB_HOST: "{{ MYSQL_HOSTNAME }}"
          WORDPRESS_DB_USER: wordpressdb
          WORDPRESS_DB_PASSWORD: "{{ MYSQL_PASSWORD }}"
          WORDPRESS_DB_NAME: mydb
      become: yes

  vars_prompt:
           - name: WORDPRESS_DB_PASSWORD
             prompt: "Enter the WordPress Database Password"
             private: yes 
