name: Terraform and Ansible CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
        env:
          TF_IN_AUTOMATION: "true"

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Output
        run: |
          cd terraform
          chmod +x run-terraform.sh
          ./run-terraform.sh    

      - name: Fetch IP from Terraform Output
        run: |
          cd terraform
          RDS_IP=$(terraform output | awk -F'"' 'NR==2 {print $2}')
          echo "RDS_IP=$RDS_IP" >> $GITHUB_ENV    

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible --version

      - name: Run Ansible Playbook
        run: |
          cd ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventory.yml setup-wordpress.yml --extra-vars=MYSQL_HOSTNAME=$RDS_IP

     

