name: Terraform and Ansible CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

          # - name: Set up Terraform
          # run: |
          # curl -fsSL https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_linux_amd64.zip -o terraform.zip
          # unzip terraform.zip
          # sudo mv terraform /usr/local/bin/
          # terraform --version
        env:
          TF_IN_AUTOMATION: "true"
  
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Output
        run: |
          cd terraform
          chmod +x run-terraform.sh
          ./run-terraform.sh    

      - name: Fetch IP from Terraform Output
        run: |
          cd terraform
          RDS_IP=$(terraform output | awk -F'"' 'NR==2 {print $2}')
          echo "RDS_IP=$RDS_IP" >> $GITHUB_ENV    

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible --version

      - name: Run Ansible Playbook
        run: |
          cd ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventory.yml setup-wordpress.yml -e MYSQL_HOSTNAME=$RDS_IP -e MYSQL_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }}

      - name: Stop Execution 2 Minutes Before Destroy
        run: sleep 120

      - name: Destroy Terraform Resources
        run: |
          cd terraform
          terraform destroy -auto-approve
     

